server {
  listen 80;
  server_name se-frontend;

  root /usr/share/nginx/html;
  index index.html;

  # SPA history 路由回退
  location / {
    try_files $uri $uri/ /index.html;
  }

  # 静态资源强缓存（可选）
  location /assets/ {
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}