apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-frontend
  namespace: se
  labels:
    app: se-frontend
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: se-frontend
  template:
    metadata:
      labels:
        app: se-frontend
    spec:
      containers:
        - name: se-frontend
          image: denerate/se-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20