apiVersion: v1
kind: Service
metadata:
  name: se-frontend
  namespace: se
  labels:
    app: se-frontend
spec:
  type: NodePort
  selector:
    app: se-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081